---
openapi: 3.0.1
info:
  title: API V1
  version: v1
basePath: "/api/v1"
securityDefinitions:
  Bearer:
    description: Generate JWT
    type: apiKey
    name: Authorization
    in: header
paths:
  "/users":
    post:
      summary: Creates new user
      tags:
      - Users
      consumes:
      - application/json
      responses:
        '201':
          description: user created
          headers:
            Authorization:
              type: string
              description: sets jwt authorization token in header
  "/videos":
    get:
      summary: shows users videos
      tags:
      - Videos
      security:
      - Bearer: []
      parameters:
      - name: page
        in: query
        type: integer
      - name: per_page
        in: query
        type: integer
      responses:
        '401':
          description: authentication failed
        '200':
          description: returns lists of users videos
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    attributes:
                      type: object
                      properties:
                        start_time:
                          type: integer
                        end_time:
                          type: integer
                        status:
                          type: string
                        original_file_url:
                          type: string
                        cropped_file_url:
                          type: string
    post:
      summary: creates video
      tags:
      - Videos
      security:
      - Bearer: []
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: start_time
        in: formData
        type: integer
      - name: end_time
        in: formData
        type: integer
      - name: video
        in: formData
        type: file
      responses:
        '401':
          description: authentication failed
        '200':
          description: creates new video
        '400':
          description: params validation error
  "/videos/{id}":
    get:
      summary: shows one video
      tags:
      - Videos
      security:
      - Bearer: []
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '401':
          description: authentication failed
        '200':
          description: returns lists of users videos
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  attributes:
                    type: object
                    properties:
                      start_time:
                        type: integer
                      end_time:
                        type: integer
                      status:
                        type: string
                      original_file_url:
                        type: string
                      cropped_file_url:
                        type: string
