default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") + "_development" %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") + "_test"%>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
